### ISSUE TITLE
Crashes after first configuration (PathTooLongException)

### ISSUE THREAD

**Issue by niol** [FTPbox/FTPbox#15]
FTPBox crashes after first configuration :

*************\* Exception Text **************
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.Security.Util.StringExpressionSet.CanonicalizePath(String path, Boolean needFullPath)
   at System.Security.Util.StringExpressionSet.CreateListFromExpressions(String[] str, Boolean needFullPath)
   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String path)
   at System.IO.FileSystemInfo.get_FullName()
   at FTPbox.Forms.fMain.LoadLocalFolders()
   at FTPbox.Forms.fMain.fMain_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by F1iX** [comment]
Unfortunately, the problem of too long path names makes FTPbox completely unusable for me, especially when syncing an encFS-encrypted folder. I am not familiar with the source code, but there might be a possibility to fix those errors by adding a "\?\" prefix as mentioned here:

"To specify an extended-length path, use the "\?\" prefix. For example, "\?\D:\very long path"." (http://msdn.microsoft.com/en-us/library/aa365247%28VS.85%29.aspx)

**Comment by Corey-M** [comment]
.NET 4.6.2 now has support for long paths... on Windows 10, once you have jumped through a [bunch of hoops][1].  Still waiting for Microsoft to recognise that long paths are actually important to us .NET developers.

While we wait for that (without holding our breaths) there are alternatives.

My personal preference, which I have used in numerous programs over the last year or so, is Peter Richie's very excellent [Pri.LongPath][2] library (on [NuGet][3]).  It replicates most of the relevant `System.IO` classes - `Directory`, `DirectoryInfo`, `File`, `FileInfo`, `Path`, etc - with calls to the Windows API methods that happily consume long paths.

In most cases it's simply a matter of changing the `using` at the top of your file, but you might need to alias some things from `System.IO`.  These are the ones aliased in `Pri.LongPath.FileInfo`:

    using FileAccess = System.IO.FileAccess;
    using FileMode = System.IO.FileMode;
    using FileStream = System.IO.FileStream;
    using StreamWriter = System.IO.StreamWriter;
    using FileShare = System.IO.FileShare;
    using FileOptions = System.IO.FileOptions;
    using StreamReader = System.IO.StreamReader;
    using FileAttributes = System.IO.FileAttributes;

If you use any of those you need to either alias them or fully specify.

[1]: https://blogs.msdn.microsoft.com/jeremykuhne/2016/07/30/net-4-6-2-and-long-paths-on-windows-10/
[2]: https://github.com/peteraritchie/LongPath
[3]: https://www.nuget.org/packages/Pri.LongPath/

**Comment by Corey-M** [comment]
So I downloaded the project and replaced all the file operations with `Pri.LongPath` and it works... but my FTP server (FileZilla Server) can't handle those long paths.  I don't have a decent Linux FTP server to test with at the moment, so I can't confirm that the code works.

The changes basically involved a blanket replace of `using System.IO;` with `using Pri.LongPath;` and adding aliases where required.  I won't be doing a pull request until I can confirm actually working.

Incidentally, the `FileSystemWatcher` class handles the long paths without modification.
