### ISSUE TITLE
Client silently crashes after a certain time

### ISSUE THREAD

**Issue by DicaxDorcas** [FTPbox/FTPbox#22]
Client will silently fail after a certain period of time. No error displayed.

**Comment by gigenthomas** [comment]
I have the same issue - Can you help ?

**Comment by gigenthomas** [comment]
Here's the error from event log : 
Application: FTPbox.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DivideByZeroException
   at System.Windows.Forms.Control.MarshaledInvoke(System.Windows.Forms.Control, System.Delegate, System.Object[], Boolean)
   at System.Windows.Forms.Control.Invoke(System.Delegate, System.Object[])
   at FTPbox.Forms.fTrayForm.<fTrayForm_Load>b__7(System.Object, FTPboxLib.TransferProgressArgs)
   at FTPboxLib.Client.ReportTransferProgress(FTPboxLib.TransferProgressArgs)
   at FTPboxLib.Client+<>c__DisplayClass11.<SafeUpload>b__d(UInt64)
   at Renci.SshNet.SftpClient+<>c__DisplayClass20.<InternalUploadFile>b__1d()
   at Renci.SshNet.SftpClient+<>c__DisplayClass24.<ExecuteThread>b__23(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by seltix5** [comment]
hello,
i'm having the same problem, how can I help debugging thins problem? where are the logs?
![image](https://user-images.githubusercontent.com/11258096/40186223-7b89ae76-59ec-11e8-9104-5d655d992fdb.png)
