### ISSUE TITLE
FTPBox crashes from time to time

### ISSUE THREAD

**Issue by lupetto3012** [FTPbox/FTPbox#51]
FTPBox crashes from time to time with following errors in the windows event log:

```
Name der fehlerhaften Anwendung: FTPbox.exe, Version: 2.6.3.1, Zeitstempel: 0x5557b55b
Name des fehlerhaften Moduls: clr.dll, Version: 4.6.1063.1, Zeitstempel: 0x5653653c
Ausnahmecode: 0xc00000fd
Fehleroffset: 0x000bee31
ID des fehlerhaften Prozesses: 0x31e4
Startzeit der fehlerhaften Anwendung: 0x01d164115ad7a684
Pfad der fehlerhaften Anwendung: C:\Program Files (x86)\FTPbox\FTPbox.exe
Pfad des fehlerhaften Moduls: C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Berichtskennung: df2c6879-1df1-457a-969f-b6cd4e4e9417
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
```

It happens minimum 10 times when using FTPBox the whole day.
I'm using Windows 10.

Any ideas?
Thank you!

**Comment by bigmonmulgrew** [comment]
I cant read that (German?)
But I'm getting the same issue with 1 errors generated at the same time.

`Log Name:      Application
Source:        .NET Runtime
Date:          25/03/2016 21:47:21
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      BigMon-PC10
Description:
Application: FTPbox.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at FTPboxLib.SyncQueue+<>c__DisplayClasse.<Add>b__9(FTPboxLib.SyncQueueItem)
   at System.Linq.Enumerable+WhereListIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at FTPboxLib.SyncQueue.Add(FTPboxLib.SyncQueueItem)
   at FTPboxLib.SyncQueue.CheckLocalFolder(FTPboxLib.SyncQueueItem)
   at FTPboxLib.SyncQueue.Add(FTPboxLib.SyncQueueItem)
   at FTPboxLib.SyncQueue.CheckLocalFolder(FTPboxLib.SyncQueueItem)
   at FTPboxLib.SyncQueue.Add(FTPboxLib.SyncQueueItem)
   at FTPbox.Forms.fMain.<UpdateDetails>b__1b()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()


Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-03-25T21:47:21.556452400Z" />
    <EventRecordID>17149</EventRecordID>
    <Channel>Application</Channel>
    <Computer>BigMon-PC10</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: FTPbox.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at FTPboxLib.SyncQueue+&lt;&gt;c__DisplayClasse.&lt;Add&gt;b__9(FTPboxLib.SyncQueueItem)
   at System.Linq.Enumerable+WhereListIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at FTPboxLib.SyncQueue.Add(FTPboxLib.SyncQueueItem)
   at FTPboxLib.SyncQueue.CheckLocalFolder(FTPboxLib.SyncQueueItem)
   at FTPboxLib.SyncQueue.Add(FTPboxLib.SyncQueueItem)
   at FTPboxLib.SyncQueue.CheckLocalFolder(FTPboxLib.SyncQueueItem)
   at FTPboxLib.SyncQueue.Add(FTPboxLib.SyncQueueItem)
   at FTPbox.Forms.fMain.&lt;UpdateDetails&gt;b__1b()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

</Data>
  </EventData>
</Event>`

`Log Name:      Application
Source:        Application Error
Date:          25/03/2016 21:47:21
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      BigMon-PC10
Description:
Faulting application name: FTPbox.exe, version: 2.6.3.1, time stamp: 0x5557b55b
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x065a2879
Faulting process ID: 0x1e50
Faulting application start time: 0x01d186dfbde1ff65
Faulting application path: C:\Program Files (x86)\FTPbox\FTPbox.exe
Faulting module path: unknown
Report ID: ab5dce08-4801-403a-8f69-1f1e22f813c3
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-03-25T21:47:21.672968500Z" />
    <EventRecordID>17150</EventRecordID>
    <Channel>Application</Channel>
    <Computer>BigMon-PC10</Computer>
    <Security />
  </System>
  <EventData>
    <Data>FTPbox.exe</Data>
    <Data>2.6.3.1</Data>
    <Data>5557b55b</Data>
    <Data>unknown</Data>
    <Data>0.0.0.0</Data>
    <Data>00000000</Data>
    <Data>c0000005</Data>
    <Data>065a2879</Data>
    <Data>1e50</Data>
    <Data>01d186dfbde1ff65</Data>
    <Data>C:\Program Files (x86)\FTPbox\FTPbox.exe</Data>
    <Data>unknown</Data>
    <Data>ab5dce08-4801-403a-8f69-1f1e22f813c3</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>`

Usinge 6.3.2 Beta
Windows 10 64 bit Full spec below[
[BIGMON-PC10.txt](https://github.com/FTPbox/FTPbox/files/190167/BIGMON-PC10.txt)
](url)

**Comment by lupetto3012** [comment]
Yesterday my FTPBox crashed only seconds after starting. I remembered that I have changed a few firewall settings for ftp passive mode minutes before the crash happened. I checked the FTP server and my firewall again and corrected all the settings for passive mode. Now FTPBox is running without crashing for hours.

**Comment by gigenthomas** [comment]
![image](https://cloud.githubusercontent.com/assets/3069429/20020891/b4d02058-a290-11e6-96fd-8f22c73d11cf.png)

FTP Box crashes after running for a while
